In [3]:
import numpy as np

In [12]:
a='basil'
a

'basil'

# WORK SPACE

## Pyramid

create a star pyramid (for loop) 

In [17]:
for  row in range(0,7):
    for space in range(7-row):
        print(' ',end='')
    for star in range(0,row):
        print('* ',end="")
    print("")

       
      * 
     * * 
    * * * 
   * * * * 
  * * * * * 
 * * * * * * 


In [22]:
a=[1,2,3],[4,56,6]
a

([1, 2, 3], [4, 56, 6])

In [23]:
metrix=np.array(a)
metrix

array([[ 1,  2,  3],
       [ 4, 56,  6]])

In [24]:
np.array(metrix)

array([[ 1,  2,  3],
       [ 4, 56,  6]])

In [25]:
np.sum(a)

72

In [36]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])